name: Staging

on:
  push:
    branches: stage

jobs:
    build-deploy:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
            node-version: "15.x"

      - name: Install dependencies
        run: npm ci
      
      - name: Linter (ESLint)
        run: npm run lint
      
      - name: Formatter (Prettier)
        run: npx prettier --check "./src/"
    
      - name: Test (Jest)
        run: CI=true npm run test

      - name: Build
        run: npm run build
      
      - name: Artifact build
        uses: actions/upload-artifact@v4.4.0
        with:
          name: build
          path: build/
          retention-days: 1

    deploy:
      runs-on: ubuntu-latest
      needs: build-deploy
      defaults:
        run:
          working-directory: terraform/environment/stage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY}}

      steps:
      - uses: actions/checkout@v4

      - name: Artifact build
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: ./build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2


      - name: Inti
        run: terraform init
      
      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan
      
      - name: Apply
        run: terraform apply -auto-approve  

      
